#!/bin/sh
inputfile="$1"
if [ -z "$2" ] ; then
    outputfile="$inputfile.mp4"
else
    outputfile="$2"
fi
echo ffmpeg -i $@/$# -c:v libsvtav1 -crf 30 -q:v 2 -c:a alac /home/zuki/ResolveMedia/Out/$#.mp4

if [ -z "$DBUS_SESSION_BUS_ADDRESS"] ; then
export DBUS_SESSION_BUS_ADDRESS=$(cat /tmp/dbus-backup)
fi
notify-send "starting conversion" "to $outputfile"

ffmpeg -i "$inputfile" -c:v libsvtav1 -crf 30 -q:v 2 -c:a alac "$outputfile.mp4" && conversionFFmpegWorked=1


if [ -z "$conversionFFmpegWorked" ] ; then
notify-send "filed to convert $inputfile"
else
notify-send "converted $inputfile" "to $outputfile" 
fi
