#!/bin/sh
while [ "$(pgrep 'dwlb')" ]; do
    fullreset="^bg()^lm()^rm()^us()^ds()^fg()"

    date="$(date "+%a %d %b %T")"

    volup="wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
    voldown="wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
    volmute="wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    vol="^bg(ff0000)^us($volup)^ds($voldown)^lm($volmute)$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/ume//')$fullreset"

    volup="wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+"
    voldown="wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%-"
    volmute="wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
    volmic="^bg()^us($volup)^ds($voldown)^lm($volmute)$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | sed 's/Volume/Mic/')$fullreset"

    dwlb -status all "$volmic $vol $date"
done
