#!/bin/sh

addtray() {
    local pidname=$1
    local text=$2
    if [ "$(pgrep -x "$pidname")" != "0" ] ; then 
        echo "^rm(pkill $pidname)$text"
    fi
}

# main loop
while [ "$(pgrep 'dwlb')" ]; do
    rs="^bg()^lm()^rm()^us()^ds()^fg()"

    date="$(date "+%a %d %b %T")"

    # speaker volume control module
    volup="wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
    voldown="wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
    volmute="wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    vol="^bg(ff000044)^us($volup)^ds($voldown)^lm($volmute)$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/ume//')"

    # mic control module
    volup="wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+"
    voldown="wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%-"
    volmute="wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
    volmic="^bg()^us($volup)^ds($voldown)^lm($volmute)$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | sed 's/Volume/Mic/')"

    # fake tray module
    tray=""
    tray="$tray $(addtray steam )"
    tray="$tray $(addtray vesktop )"


    # dwlb -status all "$volmic $rs$vol $rs$date"
    dwlb -status all "$tray  $date"
done
