#!/usr/bin/sh

self="$0"
addtray() {
    local pidname=$1
    local text=$2
    if [ "$(pgrep -x "$pidname")" ] ; then 
        # echo "^rm(pkill $pidname)$text"
        echo " ^rm(notify-send $pidname)$text"
    fi
}
oldvol=""
# main loop
while [ "$(pgrep -x 'dwlb')" ]; do
    rs="^bg()^lm()^rm()^us()^ds()^fg()"

    date="$(date "+%a %d %b %H:%M")"

    # speaker volume control module
    volup="dwl_audio.sh 5%+"
    voldown="dwl_audio.sh 5%-"
    volmute="dwl_audio.sh toggle"
    voltext=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/Volume://')
    if [ -z "$(echo "$voltext" | grep "MUTED" )" ] ; then
        vol="^bg()^us($volup)^ds($voldown)^lm($volmute)󰕾$voltext"
    else
        set -- $voltext
        vol="^bg()^us($volup)^ds($voldown)^lm($volmute)󰖁 $1"
    fi

    # mic control module
    volup="wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+ && $self"
    voldown="wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%- && $self"
    volmute="wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && $self"
    # volmic="^bg()^us($volup)^ds($voldown)^lm($volmute)$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | sed 's/Volume://')"
    voltext="$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | sed 's/Volume://')"
    if [ -z "$(echo "$voltext" | grep "MUTED" )" ] ; then
        volmic="^bg()^us($volup)^ds($voldown)^lm($volmute)$voltext"
    else
        set -- $voltext
        volmic="^bg()^us($volup)^ds($voldown)^lm($volmute) $1"
    fi

    # fake tray module
    tray=""
    tray="$tray$rs$(addtray steam )"
    tray="$tray$rs$(addtray equibop )"
    tray="$tray$rs$(addtray vesktop.bin )"

    dwlb -status all "$tray$rs $vol $rs$volmic$rs $date"

    # title
    pstatus="$(playerctl status)"
    if [ "$pstatus" = "Playing" ] ; then
        picon=""
    elif [ "$pstatus" = "Paused" ]; then
        picon=""
    fi
    if [ -n "$picon" ] ; then
        album="$(playerctl metadata album)"
        if [ -n "$album" ] ; then
            album="$album - "
        fi
        dwlb -title all "^lm(playerctl play-pause && $self)$picon $album$(playerctl metadata title)"
    else 
        dwlb -title all " "
    fi

    # dwlb -status all "$tray  $date"
    if [ "$1" = "once" ] ; then
        exit
    fi
    sleep 1

done
