#!/usr/bin/sh
loop=true
while [ $loop = true ] ; do
    if [ -f "Makefile" ] || [ -f "makefile" ] ; then
        exec make $@
    fi
    if [ "$PWD" = "/" ] ; then
        loop=false
    else
        cd ..
    fi
done
