#!/usr/bin/sh
loop=true
while [ $loop = true ] ; do
    if [ -f "nob" ] ; then
        exec ./nob $@
    fi
    if [ -f "nob.c" ] ; then
        echo "cc nob.c -o nob"
        cc nob.c -o nob || die "failed to compile nob"
        exec ./nob $@
    fi
    if [ -f "Makefile" ] || [ -f "makefile" ] ; then
        exec make $@
    fi
    if [ "$PWD" = "/" ] ; then
        loop=false
    else
        cd ..
    fi
done
echo "failed to find makefile/nob"
exit 5
