#!/bin/bash

nproc=$(nproc)
str="$nproc:0"
for (( i=1; i<$nproc; i++ ))
do  
    str="$str,$i"
done
echo $str
# export WINE_CPU_TOPOLOGY="$str"
# export WINE_CPU_TOPOLOGY=16:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
